### ISSUE TITLE
Error when using with babel-polyfill as an Entry

### ISSUE THREAD

**Issue by jungrafael** [aduth/resolve-entry-modules-webpack-plugin#1]
When babel-polyfill is also in the entry, it simple does not work. Webpack is unable to resolve the paths based on the entries, just as if the plugin was not installed at all.

This happens because the context path and the entry root path are the same.

**Comment by jungrafael** [comment]
I was able to solve this problem here (by filtering the entries):
https://github.com/jungrafael/resolve-entry-modules-webpack-plugin

Should I make a Pull Request?

**Comment by aduth** [comment]
Thanks for raising this. Could you share the relevant part of your config (the `entry`) ?

I'm wondering if it might be an issue here:

https://github.com/aduth/resolve-entry-modules-webpack-plugin/blob/d2881fb33c948418eb4f85eaddcdc658c213b99b/index.js#L57

In that we'd typically expect the entry to point to a specific file, but you'd include the polyfill as simply `babel-polyfill`, so `dirname` would actually produce the parent directory.

```js
dirname( resolve( '.', 'babel-polyfill' ) );
// '/path/to/code'

dirname( resolve( '.', './src/index.js' ) );
// '/path/to/code/src'
```

And since each sub-module would contain the parent directory's path...

https://github.com/aduth/resolve-entry-modules-webpack-plugin/blob/d2881fb33c948418eb4f85eaddcdc658c213b99b/index.js#L68-L72

It would try to resolve from the current working directory of the project and fail.

...or at least the theory goes 😄  I will try to dig in later this evening.

**Comment by jungrafael** [comment]
Exactly that's the problem!
I was already having react hot loader in the entry and it wasn't an issue. But that is because it has an `/` on the name. Here is my entry file:

```javascript
const devServerClient = [
  'babel-polyfill',

  'react-hot-loader/patch',
  'webpack-dev-server/client?' + publicPath,
  'webpack/hot/only-dev-server'
];

  entry: {
    app: devServerClient.concat([
      web('app/main.js')
    ]),
    admin: devServerClient.concat([
      web('admin/main.js')
    ])
  }
```
 
I cannot have the `babel-polyfill` in the `main.js` because of the strict execution order: babel-polyfill -> react hot reloader -> app

How would it be the best way to solve this issue? My approach was filtering the entries by their path, but I'm not sure if there isn't a better way.

Thanks!

**Comment by aduth** [comment]
A few ideas come to mind:

1. Resolve path via `require.resolve` instead of the current resolution behavior:

```js
require.resolve( 'babel-polyfill' );
// '/path/to/code/node_modules/babel-polyfill/lib/index.js'

require.resolve( './src/index.js' );
// '/path/to/code/src/index.js'
```

Downside is that this means resolve occurs from the directory of the `main`, in this case `node_modules/babel-polyfill/lib`, where it might be expected to be `node_modules/babel-polyfill`.

2. Detect whether entry path is a node module (how?) and point to it's root directory within `node_modules` (traverse upward from `require.resolve` file directory until `package.json` is found?)

3. Detect whether entry point is a node module and simply ignore it.
